version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - '30300:80'
    depends_on:
      wordpress-db:
        condition: service_healthy
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD={{sullaServicePassword}}
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html
    restart: unless-stopped

  wordpress-db:
    image: mariadb:10.11
    container_name: wordpress-db
    restart: unless-stopped
    ports:
      - '30301:3306'
    volumes:
      - wordpress-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{sullaServicePassword}}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD={{sullaServicePassword}}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  wordpress-data:
  wordpress-db-data:
