services:
  windmill-server:
    image: ghcr.io/windmill-labs/windmill:main
    pull_policy: always
    container_name: sulla_windmill_server
    restart: unless-stopped
    ports:
      - "30130:8000"
    environment:
      - DATABASE_URL=postgres://sulla:{{sullaServicePassword|urlencode}}@host.docker.internal:30116/windmill?sslmode=disable
      - MODE=server
    volumes:
      - windmill-worker-logs:/tmp/windmill/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5

  windmill-worker:
    image: ghcr.io/windmill-labs/windmill:main
    pull_policy: always
    container_name: sulla_windmill_worker
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    environment:
      - DATABASE_URL=postgres://sulla:{{sullaServicePassword|urlencode}}@host.docker.internal:30116/windmill?sslmode=disable
      - MODE=worker
      - WORKER_GROUP=default
      - FAVOR_UNSHARE_PID=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - windmill-worker-cache:/tmp/windmill/cache
      - windmill-worker-logs:/tmp/windmill/logs

  windmill-worker-native:
    image: ghcr.io/windmill-labs/windmill:main
    pull_policy: always
    container_name: sulla_windmill_worker_native
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    environment:
      - DATABASE_URL=postgres://sulla:{{sullaServicePassword|urlencode}}@host.docker.internal:30116/windmill?sslmode=disable
      - MODE=worker
      - WORKER_GROUP=native
      - NATIVE_MODE=true
      - NUM_WORKERS=8
      - SLEEP_QUEUE=200
    volumes:
      - windmill-worker-logs:/tmp/windmill/logs

  windmill-lsp:
    image: ghcr.io/windmill-labs/windmill-extra:latest
    pull_policy: always
    container_name: sulla_windmill_lsp
    restart: unless-stopped
    expose:
      - 3001
    environment:
      - ENABLE_LSP=true
      - ENABLE_MULTIPLAYER=false
      - ENABLE_DEBUGGER=false
    volumes:
      - windmill-lsp-cache:/pyls/.cache

volumes:
  windmill-worker-cache:
  windmill-worker-logs:
  windmill-lsp-cache:
