version: "3.8"

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports:
      - "30210:32400"
    volumes:
      - plex-config:/config
      - {{path.movies}}:/data/movies
      - {{path.music}}:/data/music
      - {{path.pictures}}:/data/pictures
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=
    restart: unless-stopped
