version: "3.8"

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "30201:8080"
    volumes:
      - stirling-data:/configs
      - ./custom:/custom
    environment:
      - SYSTEM_LANGUAGE=en-GB
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped

volumes:
  stirling-data:
