name: affine

services:
  affine:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine-server
    ports:
      - '30295:3010'
    depends_on:
      affine-postgres:
        condition: service_healthy
      affine-migration:
        condition: service_completed_successfully
    volumes:
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=host.docker.internal
      - REDIS_SERVER_PORT=30117
      - DATABASE_URL=postgresql://affine:{{sullaServicePassword|urlencode}}@affine-postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
      - AFFINE_SERVER_EXTERNAL_URL=http://localhost:30295
      - NODE_ENV=production
    restart: unless-stopped

  affine-migration:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine-migration-job
    volumes:
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=host.docker.internal
      - REDIS_SERVER_PORT=30117
      - DATABASE_URL=postgresql://affine:{{sullaServicePassword|urlencode}}@affine-postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      affine-postgres:
        condition: service_healthy

  affine-postgres:
    image: pgvector/pgvector:pg16
    container_name: affine-postgres
    restart: unless-stopped
    ports:
      - '30296:5432'
    volumes:
      - affine-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: '{{sullaServicePassword}}'
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'affine', '-d', 'affine']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  affine-storage:
  affine-config:
  affine-postgres-data:
